
export const TODO = {
    ADD: 'ADD_TODO',
    REORDER: "REORDER_TODO",
    REMOVE: "REMOVE_TODO",
    REMOVE_COPLETED: "REMOVE_COMPLETED_TODO",
    TOGGLE_STATUS: "TOGGLE_STATUS_TODO"
}


export const WIDGET = {
    UPDATE_CONFIG: 'UPDATE_CONFIG',
    REMOVE_WIDGET: "REMOVE_WIDGET"
}